# Generated by Django 3.0 on 2022-11-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20221108_1146'),

    ]


    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles_profile',
        ),
    ]
