# Generated by Django 3.0 on 2022-11-05 10:35

from django.db import migrations


def transfer_old_address_in_new_table(old_address, NewAddress):

    new_address = NewAddress(
        id=old_address.id,
        number=old_address.number,
        street=old_address.street,
        city=old_address.city,
        state=old_address.state,
        zip_code=old_address.zip_code,
        country_iso_code=old_address.country_iso_code
    )
    new_address.save()


def add_datas(apps, schema_editors):
    OldAddress = apps.get_model("oc_lettings_site", "Address")
    NewAddress = apps.get_model("lettings", "Address")
    for old_address in OldAddress.objects.all():
        transfer_old_address_in_new_table(old_address, NewAddress)


def remove_datas(apps, schema_editors):

    NewAddress = apps.get_model("lettings", "Address")
    for new_address in NewAddress.objects.all():
        new_address.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_datas, remove_datas)
    ]
