# Generated by Django 3.0 on 2022-11-05 10:35

from django.db import migrations
from oc_lettings_site.models import Address as OldAddress

from lettings.models import Address as NewAddress



def transfer_old_address_in_new_table(oldaddress: OldAddress):
    newaddress = NewAddress(
        id=oldaddress.id,
        number=oldaddress.number,
        street=oldaddress.street,
        city=oldaddress.city,
        state=oldaddress.state,
        zip_code=oldaddress.zip_code,
        country_iso_code=oldaddress.country_iso_code
    )
    newaddress.save()


def add_datas(apps, schema_editors):
    Old_address = apps.get_model("oc_lettings_site", "Address")

    for oldaddress in Old_address.objects.all():
        transfer_old_address_in_new_table(oldaddress)



def remove_datas(apps, schema_editors):


    NewAddress = apps.get_model("lettings", "Address")
    for newaddress in NewAddress.objects.all():
        newaddress.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(add_datas, remove_datas)
    ]
