# Generated by Django 3.0 on 2022-11-05 14:03

from django.db import migrations

from oc_lettings_site.models import Letting as OldLetting
from lettings.models import Letting as NewLetting, Address


def transfer_old_letting_in_new_table(oldletting: OldLetting, newaddress: Address):
    newletting = NewLetting(
        id=oldletting.id,
        title=oldletting.title,
        address_id=newaddress.id,
    )

    newletting.save()

def add_datas(apps, schema_editors):

    Old_letting = apps.get_model("oc_lettings_site", "Letting")
    NewAddress = apps.get_model("lettings", "Address")
    for old_letting in Old_letting.objects.all():
        newaddress = NewAddress.objects.get(pk=old_letting.address.id)
        transfer_old_letting_in_new_table(old_letting, newaddress)

def remove_datas(apps, schema_editors):

    NewLetting = apps.get_model("lettings", "Letting")
    for newletting in NewLetting.objects.all():
        newletting.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_auto_20221105_1035'),
    ]

    operations = [
        migrations.RunPython(add_datas, remove_datas)
    ]
